language: java

jdk:
  - oraclejdk8
#  - openjdk7 # Disabled to avoid error java.security.NoSuchProviderException: no such provider: SunEC...
#  - oraclejdk7
# $ jdk_switcher use oraclejdk7
# Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
# update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
# ...
# ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle
#
#  - openjdk6 # gradle 3.1 requires java 7

before_script:
  - chmod +x gradlew
script:
  - ./gradlew check --info
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
